# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_eng.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class add_eng:
    def __init__(self,centralwidget,verticalLayout):
        
        self.centralwidget = centralwidget
        self.verticalLayout = verticalLayout
        self.frame = QtWidgets.QFrame()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_eng_layout = QtWidgets.QVBoxLayout()
        self.add_eng_layout.setObjectName("add_eng_layout")
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setObjectName("header_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.header_layout.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem1)
        self.add_eng_layout.addLayout(self.header_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.add_eng_layout.addItem(spacerItem2)
        self.data_layout_1 = QtWidgets.QHBoxLayout()
        self.data_layout_1.setContentsMargins(3, -1, 3, -1)
        self.data_layout_1.setObjectName("data_layout_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.data_layout_1.addWidget(self.label)
        self.fname = QtWidgets.QLineEdit(self.centralwidget)
        self.fname.setFrame(False)
        self.fname.setObjectName("fname")
        self.data_layout_1.addWidget(self.fname)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.data_layout_1.addWidget(self.label_2)
        self.mname = QtWidgets.QLineEdit(self.centralwidget)
        self.mname.setFrame(False)
        self.mname.setObjectName("mname")
        self.data_layout_1.addWidget(self.mname)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.data_layout_1.addWidget(self.label_3)
        self.lname = QtWidgets.QLineEdit(self.centralwidget)
        self.lname.setFrame(False)
        self.lname.setObjectName("lname")
        self.data_layout_1.addWidget(self.lname)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.data_layout_1.addWidget(self.label_4)
        self.dep = QtWidgets.QComboBox(self.centralwidget)
        self.dep.setStyleSheet("background-color: rgb(252, 255, 255);")
        self.dep.setFrame(False)
        self.dep.setObjectName("dep")
        self.data_layout_1.addWidget(self.dep)
        self.data_layout_1.setStretch(0, 1)
        self.data_layout_1.setStretch(1, 5)
        self.data_layout_1.setStretch(2, 1)
        self.data_layout_1.setStretch(3, 5)
        self.data_layout_1.setStretch(4, 1)
        self.data_layout_1.setStretch(5, 5)
        self.data_layout_1.setStretch(6, 1)
        self.data_layout_1.setStretch(7, 5)
        self.add_eng_layout.addLayout(self.data_layout_1)
        self.data_layout_2 = QtWidgets.QHBoxLayout()
        self.data_layout_2.setContentsMargins(3, -1, 4, -1)
        self.data_layout_2.setObjectName("data_layout_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.data_layout_2.addWidget(self.label_10)
        self.salary = QtWidgets.QLineEdit(self.centralwidget)
        self.salary.setObjectName("salary")
        self.data_layout_2.addWidget(self.salary)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.data_layout_2.addWidget(self.label_12)
        self.whour = QtWidgets.QLineEdit(self.centralwidget)
        self.whour.setObjectName("whour")
        self.data_layout_2.addWidget(self.whour)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.data_layout_2.addWidget(self.label_7)
        self.SSD = QtWidgets.QLineEdit(self.centralwidget)
        self.SSD.setObjectName("SSD")
        self.data_layout_2.addWidget(self.SSD)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.data_layout_2.addWidget(self.label_13)
        self.birthdate = QtWidgets.QDateEdit(self.centralwidget)
        self.birthdate.setCalendarPopup(True)
        self.birthdate.setObjectName("birthdate")
        self.data_layout_2.addWidget(self.birthdate)
        self.data_layout_2.setStretch(0, 1)
        self.data_layout_2.setStretch(1, 5)
        self.data_layout_2.setStretch(2, 1)
        self.data_layout_2.setStretch(3, 5)
        self.data_layout_2.setStretch(4, 1)
        self.data_layout_2.setStretch(5, 5)
        self.data_layout_2.setStretch(6, 1)
        self.data_layout_2.setStretch(7, 5)
        self.add_eng_layout.addLayout(self.data_layout_2)
        self.data_layout_3 = QtWidgets.QHBoxLayout()
        self.data_layout_3.setContentsMargins(3, -1, 3, -1)
        self.data_layout_3.setObjectName("data_layout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.data_layout_3.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.data_layout_3.addWidget(self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.data_layout_3.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.data_layout_3.addWidget(self.lineEdit_3)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.data_layout_3.addWidget(self.label_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.data_layout_3.addWidget(self.lineEdit_4)
        self.data_layout_3.setStretch(0, 1)
        self.data_layout_3.setStretch(1, 5)
        self.data_layout_3.setStretch(2, 1)
        self.data_layout_3.setStretch(3, 5)
        self.data_layout_3.setStretch(4, 1)
        self.data_layout_3.setStretch(5, 5)
        self.add_eng_layout.addLayout(self.data_layout_3)
        self.save_layout = QtWidgets.QHBoxLayout()
        self.save_layout.setObjectName("save_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.save_layout.addItem(spacerItem3)
        self.Save_bt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Save_bt.setFont(font)
        self.Save_bt.setFlat(True)
        self.Save_bt.setObjectName("Save_bt")
        self.save_layout.addWidget(self.Save_bt)
        self.Cancel_bt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cancel_bt.setFont(font)
        self.Cancel_bt.setDefault(False)
        self.Cancel_bt.setFlat(True)
        self.Cancel_bt.setObjectName("Cancel_bt")
        self.save_layout.addWidget(self.Cancel_bt)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.save_layout.addItem(spacerItem4)
        self.add_eng_layout.addLayout(self.save_layout)
        self.add_eng_layout.setStretch(0, 4)
        self.add_eng_layout.setStretch(1, 1)
        self.add_eng_layout.setStretch(2, 6)
        self.add_eng_layout.setStretch(3, 6)
        self.add_eng_layout.setStretch(4, 6)
        self.add_eng_layout.setStretch(5, 6)
        self.verticalLayout_2.addLayout(self.add_eng_layout)
        self.frame.setLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame.hide()
        self.label_6.setText( "Add d")
        self.label.setText(" F Name")
        self.label_2.setText( "M Name ")
        self.label_3.setText( "L Name ")
        self.label_4.setText( "Dep")
        self.label_10.setText( " Salary")
        self.label_12.setText( "Work hours")
        self.label_7.setText( "SSD")
        self.label_13.setText( "birth date")
        self.birthdate.setDisplayFormat( "yyyy-MM-dd")
        self.label_5.setText( "country")
        self.label_8.setText( "city")
        self.label_9.setText( "address")
        self.Save_bt.setText( "Save")
        self.Cancel_bt.setText( "Cancel")

        self.Cancel_bt.clicked.connect(self.hide)

    def fill_dep(self,func):
        deps = func()
        for i in deps:
            self.dep.addItem(i[0])


    def get_date(self):
        data = []
        data.append(self.fname.text())
        data.append(self.mname.text())
        data.append(self.lname.text())
        data.append(self.lineEdit_5.text())
        data.append(self.lineEdit_3.text())
        data.append(self.lineEdit_4.text())
        data.append(self.salary.text())
        data.append(self.whour.text())
        data.append(int(self.dep.currentIndex())+ 1)
        data.append(self.birthdate.date().toPyDate())
        data.append(self.SSD.text())
        #
        

        return data 

    def hide(self):
        self.frame.hide()

    def show(self,employee):
        self.label_6.setText(f"Add {employee}")
        self.frame.show()

    def connect_save(self,func):
        self.Save_bt.clicked.connect(func)
