# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class main_page:
    def  __init__(self,centralwidget,verticalLayout,list_,fill_table,combo):

        self.centralwidget = centralwidget
        self.verticalLayout_2 = verticalLayout
        self.list=list_
        self.combo =combo
        self.frame = QtWidgets.QFrame()
        self.fill = fill_table
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.emerg_layout = QtWidgets.QVBoxLayout()
        self.emerg_layout.setObjectName("emerg_layout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.emerg_layout.addWidget(self.label_5)
        self.emergy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.emergy_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.emergy_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.emergy_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/emergency.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emergy_btn.setIcon(icon)
        self.emergy_btn.setIconSize(QtCore.QSize(180, 100))
        self.emergy_btn.setFlat(True)
        self.emergy_btn.setObjectName("emergy_btn")
        self.emerg_layout.addWidget(self.emergy_btn)
        self.horizontalLayout.addLayout(self.emerg_layout)
        self.or_layout = QtWidgets.QVBoxLayout()
        self.or_layout.setObjectName("or_layout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.or_layout.addWidget(self.label)
        self.or_btn = QtWidgets.QPushButton(self.centralwidget)
        self.or_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.or_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/or.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.or_btn.setIcon(icon1)
        self.or_btn.setIconSize(QtCore.QSize(180, 95))
        self.or_btn.setFlat(True)
        self.or_btn.setObjectName("or_btn")
        self.or_layout.addWidget(self.or_btn)
        self.horizontalLayout.addLayout(self.or_layout)
        self.icu_layout = QtWidgets.QVBoxLayout()
        self.icu_layout.setObjectName("icu_layout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.icu_layout.addWidget(self.label_2)
        self.icubtn = QtWidgets.QPushButton(self.centralwidget)
        self.icubtn.setMinimumSize(QtCore.QSize(0, 100))
        self.icubtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icu.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icubtn.setIcon(icon2)
        self.icubtn.setIconSize(QtCore.QSize(180, 100))
        self.icubtn.setFlat(True)
        self.icubtn.setObjectName("icubtn")
        self.icu_layout.addWidget(self.icubtn)
        self.horizontalLayout.addLayout(self.icu_layout)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.frame1 = QtWidgets.QFrame()
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_8.setBaseSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.eng_btn = QtWidgets.QPushButton(self.centralwidget)
        self.eng_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.eng_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/eng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eng_btn.setIcon(icon3)
        self.eng_btn.setIconSize(QtCore.QSize(100, 100))
        self.eng_btn.setFlat(True)
        self.eng_btn.setObjectName("eng_btn")
        self.verticalLayout_7.addWidget(self.eng_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.tech_btn = QtWidgets.QPushButton(self.centralwidget)
        self.tech_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.tech_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/technician.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tech_btn.setIcon(icon4)
        self.tech_btn.setIconSize(QtCore.QSize(100, 100))
        self.tech_btn.setFlat(True)
        self.tech_btn.setObjectName("tech_btn")
        self.verticalLayout_6.addWidget(self.tech_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.eq_btn = QtWidgets.QPushButton(self.centralwidget)
        self.eq_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.eq_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/eq.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eq_btn.setIcon(icon5)
        self.eq_btn.setIconSize(QtCore.QSize(100, 100))
        self.eq_btn.setFlat(True)
        self.eq_btn.setObjectName("eq_btn")
        self.verticalLayout_5.addWidget(self.eq_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.ppm_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ppm_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.ppm_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/ppm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ppm_btn.setIcon(icon6)
        self.ppm_btn.setIconSize(QtCore.QSize(100, 100))
        self.ppm_btn.setFlat(True)
        self.ppm_btn.setObjectName("ppm_btn")
        self.verticalLayout_8.addWidget(self.ppm_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.aily_btn = QtWidgets.QPushButton(self.centralwidget)
        self.aily_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.aily_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/daily_inspection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aily_btn.setIcon(icon7)
        self.aily_btn.setIconSize(QtCore.QSize(100, 100))
        self.aily_btn.setFlat(True)
        self.aily_btn.setObjectName("aily_btn")
        self.verticalLayout_4.addWidget(self.aily_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.purchase_btn = QtWidgets.QPushButton(self.centralwidget)
        self.purchase_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.purchase_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/purchase.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.purchase_btn.setIcon(icon8)
        self.purchase_btn.setIconSize(QtCore.QSize(100, 100))
        self.purchase_btn.setFlat(True)
        self.purchase_btn.setObjectName("purchase_btn")
        self.verticalLayout_3.addWidget(self.purchase_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.frame1.setLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame1)
        self.frame.setLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.dep_li = [self.emergy_btn,self.or_btn,self.icubtn]
        self.options_li=[self.eng_btn,self.tech_btn,self.eq_btn,self.ppm_btn,self.aily_btn,self.purchase_btn]
        self.label_5.setText("Emergency")
        self.label.setText("OR")
        self.label_2.setText("ICU")
        self.label_8.setText("Eng")
        self.label_7.setText("Tech")
        self.label_6.setText(" Equip")
        self.label_9.setText("      PPM")
        self.label_4.setText("Daily Inspec")
        self.label_3.setText("Purchase ")
        self.index=[3,4,2,8,7,9]
        self.names=['engineer','technician','equipement','ppm','daily_inspection','purchase']
        self.dep=0
        self.dep_li[0].clicked.connect(lambda:self.select_dp(1))
        self.dep_li[1].clicked.connect(lambda:self.select_dp(2))
        self.dep_li[2].clicked.connect(lambda:self.select_dp(3))
        self.options_li[0].clicked.connect(lambda:self.select_option(0))
        self.options_li[1].clicked.connect(lambda:self.select_option(1))
        self.options_li[2].clicked.connect(lambda:self.select_option(2))
        self.options_li[3].clicked.connect(lambda:self.select_option(3))
        self.options_li[4].clicked.connect(lambda:self.select_option(4))
        self.options_li[5].clicked.connect(lambda:self.select_option(5))
        
    def select_dp(self,ind):
        self.dep=ind
        self.frame1.show()
    def select_option(self,ind):
        self.list.setCurrentRow(self.index[ind])
        #self.fill(self.names[ind],self.index[ind])
        self.combo.setCurrentIndex(self.dep)

    def hide(self):
        self.frame.hide()
