# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppm_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class add_ppm:
    def __init__(self,centralwidget,verticalLayout):
        self.centralwidget =  centralwidget
        self.container =verticalLayout
        self.frame =    QtWidgets.QFrame()
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.control_layout = QtWidgets.QHBoxLayout()
        self.control_layout.setContentsMargins(8, -1, 8, -1)
        self.control_layout.setObjectName("control_layout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.control_layout.addWidget(self.label)
        self.equipement = QtWidgets.QComboBox(self.centralwidget)
        self.equipement.setObjectName("equipement")
        self.control_layout.addWidget(self.equipement)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.control_layout.addWidget(self.label_2)
        self.departement = QtWidgets.QComboBox(self.centralwidget)
        self.departement.setObjectName("departement")
        self.control_layout.addWidget(self.departement)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.control_layout.addWidget(self.label_3)
        self.engineer = QtWidgets.QComboBox(self.centralwidget)
        self.engineer.setObjectName("engineer")
        self.control_layout.addWidget(self.engineer)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.control_layout.addWidget(self.label_4)
        self.technician = QtWidgets.QComboBox(self.centralwidget)
        self.technician.setObjectName("technician")
        self.control_layout.addWidget(self.technician)
        self.control_layout.setStretch(1, 1)
        self.control_layout.setStretch(3, 1)
        self.control_layout.setStretch(5, 1)
        self.control_layout.setStretch(7, 1)
        self.verticalLayout.addLayout(self.control_layout)
        self.power_layout = QtWidgets.QHBoxLayout()
        self.power_layout.setContentsMargins(5, -1, 5, -1)
        self.power_layout.setObjectName("power_layout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.power_layout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.power_layout.addWidget(self.label_6)
        self.is_battery_fault = QtWidgets.QCheckBox(self.centralwidget)
        self.is_battery_fault.setObjectName("is_battery_fault")
        self.power_layout.addWidget(self.is_battery_fault)
        self.battery_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.battery_problem.setObjectName("battery_problem")
        self.power_layout.addWidget(self.battery_problem)
        self.is_cable_fault = QtWidgets.QCheckBox(self.centralwidget)
        self.is_cable_fault.setObjectName("is_cable_fault")
        self.power_layout.addWidget(self.is_cable_fault)
        self.cable_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.cable_problem.setObjectName("cable_problem")
        self.power_layout.addWidget(self.cable_problem)
        self.is_circuit_fault = QtWidgets.QCheckBox(self.centralwidget)
        self.is_circuit_fault.setObjectName("is_circuit_fault")
        self.power_layout.addWidget(self.is_circuit_fault)
        self.circuit_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.circuit_problem.setObjectName("circuit_problem")
        self.power_layout.addWidget(self.circuit_problem)
        self.power_layout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.power_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.is_software_fault = QtWidgets.QCheckBox(self.centralwidget)
        self.is_software_fault.setObjectName("is_software_fault")
        self.horizontalLayout_2.addWidget(self.is_software_fault)
        self.software_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.software_problem.setObjectName("software_problem")
        self.horizontalLayout_2.addWidget(self.software_problem)
        self.is_incorrect_output = QtWidgets.QCheckBox(self.centralwidget)
        self.is_incorrect_output.setObjectName("is_incorrect_output")
        self.horizontalLayout_2.addWidget(self.is_incorrect_output)
        self.output_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.output_problem.setObjectName("output_problem")
        self.horizontalLayout_2.addWidget(self.output_problem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(80, -1, 8, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.is_internal_malfunction = QtWidgets.QCheckBox(self.centralwidget)
        self.is_internal_malfunction.setObjectName("is_internal_malfunction")
        self.horizontalLayout_3.addWidget(self.is_internal_malfunction)
        self.internal_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.internal_problem.setObjectName("internal_problem")
        self.horizontalLayout_3.addWidget(self.internal_problem)
        self.connection_problem = QtWidgets.QCheckBox(self.centralwidget)
        self.connection_problem.setObjectName("connection_problem")
        self.horizontalLayout_3.addWidget(self.connection_problem)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_3.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.is_current_leak = QtWidgets.QCheckBox(self.centralwidget)
        self.is_current_leak.setObjectName("is_current_leak")
        self.horizontalLayout_4.addWidget(self.is_current_leak)
        self.is_physical_leak = QtWidgets.QCheckBox(self.centralwidget)
        self.is_physical_leak.setObjectName("is_physical_leak")
        self.horizontalLayout_4.addWidget(self.is_physical_leak)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.is_part_not_functionning = QtWidgets.QCheckBox(self.centralwidget)
        self.is_part_not_functionning.setObjectName("is_part_not_functionning")
        self.horizontalLayout_5.addWidget(self.is_part_not_functionning)
        self.part_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.part_problem.setObjectName("part_problem")
        self.horizontalLayout_5.addWidget(self.part_problem)
        self.is_replace_part = QtWidgets.QCheckBox(self.centralwidget)
        self.is_replace_part.setObjectName("is_replace_part")
        self.horizontalLayout_5.addWidget(self.is_replace_part)
        self.part_replaced = QtWidgets.QLineEdit(self.centralwidget)
        self.part_replaced.setObjectName("part_replaced")
        self.horizontalLayout_5.addWidget(self.part_replaced)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.is_continous_alarm = QtWidgets.QCheckBox(self.centralwidget)
        self.is_continous_alarm.setObjectName("is_continous_alarm")
        self.horizontalLayout_6.addWidget(self.is_continous_alarm)
        self.cointinous_alarm_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.cointinous_alarm_problem.setObjectName("cointinous_alarm_problem")
        self.horizontalLayout_6.addWidget(self.cointinous_alarm_problem)
        self.is_no_alarm = QtWidgets.QCheckBox(self.centralwidget)
        self.is_no_alarm.setObjectName("is_no_alarm")
        self.horizontalLayout_6.addWidget(self.is_no_alarm)
        self.no_alarm_problem = QtWidgets.QLineEdit(self.centralwidget)
        self.no_alarm_problem.setObjectName("no_alarm_problem")
        self.horizontalLayout_6.addWidget(self.no_alarm_problem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.cost = QtWidgets.QLineEdit(self.centralwidget)
        self.cost.setObjectName("cost")
        self.horizontalLayout_7.addWidget(self.cost)
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setCalendarPopup(True)
        self.date.setDisplayFormat( "yyyy-MM-dd")
        self.date.setObjectName("date")
        self.horizontalLayout_7.addWidget(self.date)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.save_layout = QtWidgets.QHBoxLayout()
        self.save_layout.setObjectName("save_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.save_layout.addItem(spacerItem3)
        self.Save_bt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Save_bt.setFont(font)
        self.Save_bt.setFlat(True)
        self.Save_bt.setObjectName("Save_bt")
        self.save_layout.addWidget(self.Save_bt)
        self.Cancel_bt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cancel_bt.setFont(font)
        self.Cancel_bt.setDefault(False)
        self.Cancel_bt.setFlat(True)
        self.Cancel_bt.setObjectName("Cancel_bt")
        self.save_layout.addWidget(self.Cancel_bt)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.save_layout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.save_layout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(9, 1)
        self.frame.setLayout(self.verticalLayout)
        self.container.addWidget(self.frame)
        self.frame.hide()

        self.label_10.setText("PPM")
        self.label.setText("equipment")
        self.label_2.setText("departement")
        self.label_3.setText("engineer")
        self.label_4.setText("technician")
        self.label_5.setText("Power:")
        self.is_battery_fault.setText("Battery Fault")
        self.is_cable_fault.setText("Cable Fault")
        self.is_circuit_fault.setText("Circuit Fault")
        self.label_7.setText("Functio Problem :")
        self.is_software_fault.setText("SoftWare")
        self.is_incorrect_output.setText("Incorrect Output")
        self.is_internal_malfunction.setText("Internal Malfunction")
        self.connection_problem.setText("Wrong Connections")
        self.label_9.setText("Leak :")
        self.is_current_leak.setText("Current Leak")
        self.is_physical_leak.setText("Physical leak")
        self.label_11.setText("Parts Problem :")
        self.is_part_not_functionning.setText("Part Not Functioning")
        self.is_replace_part.setText("Replace Part")
        self.label_13.setText("Alarm Problem :")
        self.is_continous_alarm.setText("Continuos Alarm")
        self.is_no_alarm.setText("No alarm")
        self.label_15.setText("Cost / Date :")
        self.Save_bt.setText( "Save")
        self.Cancel_bt.setText( "Cancel")

        self.fill_eq_func=0
        self.Cancel_bt.clicked.connect(self.hide)
        self.departement.currentIndexChanged.connect(self.change_eq)

    def fill_dep(self,func):
        deps = func()
        self.departement.addItem('None')
        for i in deps:
            self.departement.addItem(i[0])
    def fill_eng(self,func):
        engs = func()
        for i in engs:
            self.engineer.addItem(i[0])

    def fill_tech(self,func):
        techs = func()
        for i in techs:
            self.technician.addItem(i[0])

    def fill_eq(self,func):
        self.equipement.clear()
        self.fill_eq_func  = func
        eqs = func(0)
        for i in eqs:
            self.equipement.addItem(i[0]+','+i[1])

    def change_eq(self):
        index = int(self.departement.currentIndex() )
        if self.fill_eq_func!=0:
            self.eq.clear()
            eqs=self.fill_eq_func(index)
            for i in eqs:
                self.eq.addItem(i[0]+','+i[1])


    def get_date(self):
        data = []
        eq = self.equipement.currentText()
        eq = eq.split(',')
        eq =eq[1]
        eq = eq[3:]

        data.append(int(eq))
        data.append(int(self.engineer.currentIndex())+ 1)
        data.append(int(self.technician.currentIndex())+ 1)
        data.append(int(self.is_battery_fault.isChecked()))
        data.append(self.battery_problem.text())
        data.append(int(self.is_circuit_fault.isChecked()))
        data.append(self.circuit_problem.text())
        data.append(int(self.is_cable_fault.isChecked()))
        data.append(self.cable_problem.text())
        data.append(int(self.is_software_fault.isChecked()))
        data.append(self.software_problem.text())       
        data.append(int(self.is_incorrect_output.isChecked()))
        data.append(self.output_problem.text())
        data.append(int(self.is_internal_malfunction.isChecked()))
        data.append(self.internal_problem.text())
        data.append(int(self.connection_problem.isChecked()))
        data.append(self.lineEdit_5.text())
        data.append(int(self.is_current_leak.isChecked()))
        data.append(int(self.is_physical_leak.isChecked()))
        data.append(int(self.is_part_not_functionning.isChecked()))
        data.append(self.part_problem.text())
        data.append(int(self.is_replace_part.isChecked()))
        data.append(self.part_replaced.text())
        data.append(int(self.is_continous_alarm.isChecked()))
        data.append(self.cointinous_alarm_problem.text() )
        data.append(int(self.is_no_alarm.isChecked()))
        data.append(self.no_alarm_problem.text() )

        if self.cost.text()!='':
            if self.cost.text().isdecimal():
                data.append(int(self.cost.text()))
            else:
                data.append(0)
        else:
            data.append(0)
        data.append(self.date.date().toPyDate())    

        return data 

    def hide(self):
        self.frame.hide()

    def show(self):
        self.frame.show()

    def connect_save(self,func):
        self.Save_bt.clicked.connect(func)