# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'purchase_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class add_purchase:
    def __init__(self,centralwidget,verticalLayout):
        self.verticalLayout1 = verticalLayout
        self.centralwidget = centralwidget
        self.frame = QtWidgets.QFrame()

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.eq_name = QtWidgets.QLineEdit(self.centralwidget)
        self.eq_name.setObjectName("eq_name")
        self.horizontalLayout.addWidget(self.eq_name)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.eng = QtWidgets.QComboBox(self.centralwidget)
        self.eng.setObjectName("eng")
        self.horizontalLayout.addWidget(self.eng)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sup = QtWidgets.QComboBox(self.centralwidget)
        self.sup.setObjectName("sup")
        self.horizontalLayout.addWidget(self.sup)
        self.add_sup = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_sup.setFont(font)
        self.add_sup.setDefault(False)
        self.add_sup.setFlat(False)
        self.add_sup.setObjectName("add_sup")
        self.horizontalLayout.addWidget(self.add_sup)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.order_date = QtWidgets.QDateEdit(self.centralwidget)
        self.order_date.setCalendarPopup(False)
        self.order_date.setObjectName("order_date")
        self.horizontalLayout_2.addWidget(self.order_date)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.expect_date = QtWidgets.QDateEdit(self.centralwidget)
        self.expect_date.setCalendarPopup(True)
        self.expect_date.setObjectName("expect_date")
        self.horizontalLayout_2.addWidget(self.expect_date)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.units_no = QtWidgets.QSpinBox(self.centralwidget)
        self.units_no.setMaximum(10000000)
        self.units_no.setObjectName("units_no")
        self.horizontalLayout_3.addWidget(self.units_no)
        self.unit_cost = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unit_cost.setFont(font)
        self.unit_cost.setObjectName("unit_cost")
        self.horizontalLayout_3.addWidget(self.unit_cost)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMaximum(10000000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.additional_cost = QtWidgets.QSpinBox(self.centralwidget)
        self.additional_cost.setMaximum(1000000)
        self.additional_cost.setObjectName("additional_cost")
        self.horizontalLayout_3.addWidget(self.additional_cost)
        self.additional_details = QtWidgets.QLineEdit(self.centralwidget)
        self.additional_details.setObjectName("additional_details")
        self.horizontalLayout_3.addWidget(self.additional_details)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setObjectName("Save")
        self.horizontalLayout_5.addWidget(self.Save)
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_5.addWidget(self.Cancel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(5, 2)
        self.frame.setLayout(self.verticalLayout)
        self.verticalLayout1.addWidget(self.frame)
        self.frame.hide()
        self.label_6.setText("Purchase Order")
        self.label.setText("Eq Name")
        self.label_2.setText("Eng")
        self.label_3.setText("Supplier")
        self.add_sup.setText("Add Supplier")
        self.label_4.setText("Order Date")
        self.order_date.setDisplayFormat("yyyy-MM-dd")
        self.label_5.setText("Expect Date")
        self.expect_date.setDisplayFormat("yyyy-MM-dd")
        self.label_9.setText("Number Of Units")
        self.unit_cost.setText("Unit Cost")
        self.label_11.setText("Additional Cost")
        self.Save.setText("Save")
        self.Cancel.setText("Cancel")
        self.Cancel.clicked.connect(self.hide)

    def fill_eng(self,func):
        engs = func()
        for i in engs:
            self.eng.addItem(i[0])

    def fill_supplier(self,func):
        self.sup.clear()
        supplier = func()
        self.sup.addItem("None")
        for i in supplier:
            self.sup.addItem(i[0])

    def get_date(self):
        data = []
        data.append(self.eq_name.text())
        data.append(int(self.eng.currentIndex())+ 1)
        data.append(int(self.sup.currentIndex()))
        data.append(self.order_date.date().toPyDate())
        data.append(self.expect_date.date().toPyDate())
        data.append(self.units_no.text())
        data.append(self.spinBox_2.text())
        data.append(self.additional_cost.text())
        data.append(self.additional_details.text())
        
        if data[0]!='' and  data[2]!=0  :
            return data
        else:
            return 0

    def hide(self):
        self.frame.hide()

    def show(self):
        self.frame.show()

    def connect_save(self,func):
        self.Save.clicked.connect(func)
    def connect_supplier(self,func):
        self.add_sup.clicked.connect(lambda:func(self.fill_supplier) )
